version: '3'
services:
  server:
    container_name: server
    image: jakeheon/moyeota
    ports:
      - 8081:8081
    restart: "always"

  nginx:
    container_name: nginx
    image: jakeheon/moyeota-nginx
    ports:
      - 80:80
    depends_on:
      - "server"