#spring:
#  profiles:
#    include: secure
#  datasource:
#    driver-class-name:
#      com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/moyeota
#    username: root
#    password: rlaxogjs8312
spring:
  profiles:
    include: secure
  datasource:
    url: jdbc:h2:tcp://localhost/~/moyeota
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles:
    include: secure
  datasource:
    url: jdbc:mariadb://moyeota-db.cn9h5fkyju6p.ap-northeast-2.rds.amazonaws.com:3306/moyeota_database
    username: admin
    password: moyeota!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
#      hbm2ddl:
#        auto: update
      ddl-auto: update
    properties:
        show_sql: true
        format_sql: true
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

univcert:
  api:
    key: 7559e79a-1806-496c-adad-77394927b6b1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  secret: RlaXoVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

oauth:
  kakao:
    client-id: 3b7fe612c8054aa522c8728a78c2eb28
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: 8uZ9AVKzSa
    client-id: YAr_BNWN5Q_wraQE0iCy
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
  google:
    client-id: 199229219883-f0gkqakb3gke9rmthdk3m13eimpobemu.apps.googleusercontent.com
    client-secret: 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
    url:
      api: https://oauth2.googleapis.com
# 거리계산을 위한 REST API 키
KAKAO:
  REST:
    API-KEY: ec0f3d7c12dec41f8f917b8b05682e5b