#spring:
#  datasource:
#    driver-class-name:
#      com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/moyeota
#    username: root
#    password: rlaxogjs8312

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/moyeota
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

univcert:
  api:
    key: 7559e79a-1806-496c-adad-77394927b6b1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  secret: RlaXoVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# OAuth 테스트를 위해서 임의로 앱을 만들었습니다. -> 이후에 모여타 앱 등록 후 client-id 변경
oauth:
  kakao:
    client-id: 3b7fe612c8054aa522c8728a78c2eb28
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: dlqyJNKOJA
    client-id: gEFBcvIBnBSrlX5PrCmk
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com
  google:
    client-id: 1080355904017-bc0ejbid1j01td1ur921cpvur768s8s5.apps.googleusercontent.com
    client-secret: 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
    url:
      api: https://oauth2.googleapis.com