name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Grant execute permission for gradlew and build
      run: |
        chmod +x gradlew
        ./gradlew build
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Copy secret
      env:
        OCCUPY_SECRET: ${{ secrets.secure_yml }}
        OCCUPY_SECRET_DIR: src/main/resources
        OCCUPY_SECRET_DIR_FILE_NAME: application-secure.yml
      run: echo $OCCUPY_SECRET | base64 --decode > $OCCUPY_SECRET_DIR/$OCCUPY_SECRET_DIR_FILE_NAME
        
    - name: init with Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew clean build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0

    - name: Docker build & push to docker repo
      run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          echo "로그인은 성공"
          docker build -t jakeheon/moyeota -f Dockerfile .
          echo "빌드 성공"
          docker push jakeheon/moyeota

    - name: Build and deploy
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.KEY }}
        envs: GITHUB_SHA
        script: |
          sudo docker stop $(sudo docker ps -aq)
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull jakeheon/moyeota
          sudo docker run -it -d -p jakeheon/moyeota
        run: |
          echo "$SSH_PEM_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no host@$SSH_KNOWN_HOSTS
          pwd
          ls
          sudo docker ps -a
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull jakeheon/moyeota
          sudo docker run -p 80:8080 jakeheon/moyeota
          sudo docker image prune -f
