name: SSL Certificate CronJob

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: "0 0 */30 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: SSL
      uses: appleboy/ssh-action@master
      id: deploy
      with:
        host: ${{ secrets.HOST }}
        username: ec2-user
        key: ${{ secrets.KEY }}
        envs: GITHUB_SHA
        run: |
          sudo letsencrypt certonly -a standalone -d moyeota.shop
